# Generated by Django 5.2.17 on 2026-10-02 19:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='商品标识')),
                ('title', models.CharField(max_length=100, verbose_name='商品名称')),
                ('description', models.TextField(verbose_name='商品描述')),
                ('question_count', models.IntegerField(verbose_name='题目数量')),
                ('estimated_minutes', models.CharField(max_length=20, verbose_name='预计用时')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='价格(分)')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='货币')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '测评商品',
                'verbose_name_plural': '测评商品',
                'db_table': 'quiz_products',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='QuizVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.CharField(max_length=50, verbose_name='版本号')),
                ('questions_hash', models.CharField(max_length=64, verbose_name='题库哈希')),
                ('scoring_hash', models.CharField(max_length=64, verbose_name='评分哈希')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否已发布')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.quizproduct', verbose_name='所属商品')),
            ],
            options={
                'verbose_name': '题库版本',
                'verbose_name_plural': '题库版本',
                'db_table': 'quiz_versions',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'version_code')},
            },
        ),
        migrations.AddField(
            model_name='quizproduct',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_current_version', to='catalog.quizversion', verbose_name='当前版本'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=50, verbose_name='题目ID')),
                ('sequence', models.IntegerField(verbose_name='题目序号')),
                ('dimension_key', models.CharField(max_length=50, verbose_name='维度键')),
                ('dimension_name', models.CharField(max_length=100, verbose_name='维度名称')),
                ('text', models.TextField(verbose_name='题目文本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='catalog.quizversion', verbose_name='所属版本')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'questions',
                'ordering': ['sequence'],
                'unique_together': {('version', 'question_id')},
            },
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(max_length=50, verbose_name='规则类型')),
                ('rule_data', models.JSONField(verbose_name='规则数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='catalog.quizversion', verbose_name='所属版本')),
            ],
            options={
                'verbose_name': '评分规则',
                'verbose_name_plural': '评分规则',
                'db_table': 'scoring_rules',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.CharField(max_length=50, verbose_name='选项ID')),
                ('sequence', models.IntegerField(verbose_name='选项序号')),
                ('text', models.TextField(verbose_name='选项文本')),
                ('scoring_data', models.JSONField(default=dict, verbose_name='评分数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.question', verbose_name='所属题目')),
            ],
            options={
                'verbose_name': '题目选项',
                'verbose_name_plural': '题目选项',
                'db_table': 'question_options',
                'ordering': ['sequence'],
                'unique_together': {('question', 'option_id')},
            },
        ),
    ]
