# Generated by Django 5.2.17 on 2026-10-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizversion',
            name='approval_state',
            field=models.CharField(choices=[('draft', '草稿'), ('preview', '客户体验'), ('approved', '审核通过')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='quizversion',
            name='content_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quizversion',
            name='report_template',
            field=models.JSONField(default=dict),
        ),
    ]
