<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { resultApi } from '@/api'
import { errorMessage } from '@/api/client'
import type { QuizResult } from '@/types'
const route = useRoute(), result = ref<QuizResult | null>(null), loading = ref(true), error = ref('')
async function load() { loading.value = true; error.value = ''; try { result.value = (await resultApi.get(String(route.params.attemptId))).data } catch(e) { error.value = errorMessage(e) } finally { loading.value = false } }
onMounted(load)
</script>
<template><div class="container page"><div v-if="loading" class="center"><span class="loading"></span><p>正在读取报告…</p></div><template v-else-if="result"><header class="result-heading"><p class="eyebrow">你的一次自我探索</p><h1>{{ result.type === 'city' ? '你的城市性格报告' : '你的心理年龄报告' }}</h1><p class="muted">{{ new Date(result.generatedAt).toLocaleString('zh-CN') }} · {{ result.isTest ? '免费体验' : '测评报告' }}</p></header><template v-if="result.type === 'city'"><article class="card result-feature stack center"><span class="badge">最佳匹配</span><h2 class="result-city">{{ result.bestMatch.cityName }}</h2><p class="result-number">{{ result.matchIndex }}<small>%</small></p><p class="muted">城市偏好匹配指数</p><p v-for="reason in result.bestMatch.matchReasons" :key="reason">{{ reason }}</p></article><section class="card stack"><h2>你的候选城市</h2><div v-for="(city, i) in result.topCandidates" :key="city.cityCode" class="candidate-row"><span class="muted">0{{ i + 1 }}</span><strong>{{ city.emoji }} {{ city.cityName }}</strong><span>{{ city.score }}%</span></div></section><section class="card stack"><h2>11 个维度的匹配</h2><p class="muted small">显示各维度与最佳匹配城市的接近程度。</p><div v-for="d in result.dimensions" :key="d.key" class="dimension"><div class="quiz-top"><span>{{ d.name }}</span><span>{{ d.score }}%</span></div><div class="progress-track"><div :style="{ width: `${d.score}%` }"></div></div></div></section></template><template v-else><article class="card result-feature stack center"><p class="result-number">{{ result.mentalAge }}<small>岁</small></p><h2>{{ result.typeName }}</h2><p class="muted">{{ result.typeDescription }}</p></article><section class="card stack"><h2>你的选择倾向</h2><p v-for="insight in result.insights" :key="insight" class="insight">{{ insight }}</p></section></template><div class="notice report-note"><p v-if="result.contentPreview">本报告采用娱乐测评规则，用于免费体验与自我观察。</p><p>{{ result.type === 'city' ? '匹配指数用于娱乐与自我观察，不代表居住成功率或科学预测。' : '心理年龄是娱乐性风格标签，不属于医疗诊断或专业心理评估。' }}</p><p>同一份答卷的结果会保持一致，输入专属密码可再次查看。</p></div><div class="actions"><router-link class="btn btn-primary" to="/">体验另一套测评</router-link><router-link class="btn btn-secondary" to="/access">使用专属密码</router-link></div></template><div v-else class="card stack"><p class="error-message" role="alert">{{ error }}</p><button class="btn btn-secondary" @click="load">重试读取报告</button><router-link to="/access">输入密码恢复权限</router-link></div></div></template>
