# Generated by Django 5.2.17 on 2026-10-02 19:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='答卷ID')),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('submitted', '已提交')], db_index=True, default='in_progress', max_length=20, verbose_name='状态')),
                ('current_question', models.IntegerField(default=1, verbose_name='当前题号')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('result_generated', models.BooleanField(default=False, verbose_name='结果已生成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='access.quizgrant', verbose_name='答题授权')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='catalog.quizproduct', verbose_name='商品')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='catalog.quizversion', verbose_name='题库版本')),
            ],
            options={
                'verbose_name': '答卷',
                'verbose_name_plural': '答卷',
                'db_table': 'quiz_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentalAgeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mental_age', models.IntegerField(verbose_name='心理年龄')),
                ('type_name', models.CharField(max_length=100, verbose_name='类型名称')),
                ('type_description', models.TextField(verbose_name='类型描述')),
                ('insights', models.JSONField(default=list, verbose_name='洞察')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mental_result', to='quiz.quizattempt', verbose_name='答卷')),
            ],
            options={
                'verbose_name': '心理年龄结果',
                'verbose_name_plural': '心理年龄结果',
                'db_table': 'mental_age_results',
            },
        ),
        migrations.CreateModel(
            name='CityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_match_city', models.CharField(max_length=50, verbose_name='最佳匹配城市')),
                ('best_match_code', models.CharField(max_length=20, verbose_name='城市代码')),
                ('match_index', models.IntegerField(verbose_name='匹配指数')),
                ('match_reasons', models.JSONField(default=list, verbose_name='匹配原因')),
                ('top_candidates', models.JSONField(default=list, verbose_name='候选城市')),
                ('dimensions', models.JSONField(default=list, verbose_name='维度分析')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='city_result', to='quiz.quizattempt', verbose_name='答卷')),
            ],
            options={
                'verbose_name': '城市测评结果',
                'verbose_name_plural': '城市测评结果',
                'db_table': 'city_results',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now=True, verbose_name='保存时间')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected_answers', to='catalog.questionoption', verbose_name='选项')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='catalog.question', verbose_name='题目')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizattempt', verbose_name='答卷')),
            ],
            options={
                'verbose_name': '答案',
                'verbose_name_plural': '答案',
                'db_table': 'answers',
                'indexes': [models.Index(fields=['attempt', 'saved_at'], name='answers_attempt_1517b9_idx')],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
