# Generated by Django 5.2.17 on 2026-10-03 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_accesscode_encrypted_code_accesscode_generation_and_more'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityresult',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='mentalageresult',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='grant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='access.quizgrant', verbose_name='答题授权'),
        ),
    ]
