# Generated by Django 5.2.17 on 2026-10-02 19:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('wechat', '微信支付')], default='wechat', max_length=20, verbose_name='支付提供商')),
                ('method', models.CharField(choices=[('native', 'Native扫码'), ('h5', 'H5支付'), ('jsapi', 'JSAPI')], max_length=20, verbose_name='支付方式')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='支付金额(分)')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='货币')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('processing', '处理中'), ('success', '成功'), ('failed', '失败'), ('refunded', '已退款')], db_index=True, default='pending', max_length=20, verbose_name='支付状态')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='交易号')),
                ('prepay_id', models.CharField(blank=True, default='', max_length=100, verbose_name='预支付ID')),
                ('code_url', models.TextField(blank=True, default='', verbose_name='二维码URL')),
                ('mweb_url', models.TextField(blank=True, default='', verbose_name='H5跳转URL')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付完成时间')),
                ('callback_data', models.JSONField(default=dict, verbose_name='回调数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='checkout.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='退款金额(分)')),
                ('reason', models.TextField(verbose_name='退款原因')),
                ('status', models.CharField(choices=[('pending', '处理中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='退款状态')),
                ('refund_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='退款单号')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='退款完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment', verbose_name='支付记录')),
            ],
            options={
                'verbose_name': '退款记录',
                'verbose_name_plural': '退款记录',
                'db_table': 'refund_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_status_426d4f_idx'),
        ),
    ]
