# Generated by Django 5.2.17 on 2026-10-02 19:33

import apps.checkout.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=apps.checkout.models.generate_order_id, editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='订单ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='订单金额(分)')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='货币')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('expired', '已过期'), ('refunded', '已退款')], db_index=True, default='pending', max_length=20, verbose_name='订单状态')),
                ('source', models.CharField(blank=True, default='', max_length=100, verbose_name='来源')),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='用户指纹')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.quizproduct', verbose_name='商品')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='orders_status_11db6c_idx'), models.Index(fields=['expires_at'], name='orders_expires_e43ed9_idx')],
            },
        ),
    ]
