# Generated by Django 5.2.17 on 2026-10-03 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_quizversion_approval_state_quizversion_content_note_and_more'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='manual_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='owner_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='product_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_state',
            field=models.CharField(choices=[('none', '未退款'), ('pending', '退款处理中'), ('success', '已退款'), ('failed', '退款失败')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.quizversion'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('testing', '测试授权'), ('expired', '已过期'), ('refunded', '已退款')], db_index=True, default='pending', max_length=20, verbose_name='订单状态'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('owner_token', 'idempotency_key'), name='unique_order_idempotency'),
        ),
    ]
