# Generated by Django 5.2.17 on 2026-10-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_idempotency_key_order_is_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
