# Generated by Django 5.2.17 on 2026-10-02 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='密码')),
                ('code_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='密码哈希')),
                ('is_activated', models.BooleanField(default=False, verbose_name='是否已激活')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='激活时间')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='是否已禁用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='access_code', to='checkout.order', verbose_name='订单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_codes', to='catalog.quizproduct', verbose_name='商品')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_codes', to='catalog.quizversion', verbose_name='题库版本')),
            ],
            options={
                'verbose_name': '专属密码',
                'verbose_name_plural': '专属密码',
                'db_table': 'access_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('access_code', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='grant', to='access.accesscode', verbose_name='密码')),
            ],
            options={
                'verbose_name': '答题授权',
                'verbose_name_plural': '答题授权',
                'db_table': 'quiz_grants',
            },
        ),
    ]
