# Generated by Django 5.2.17 on 2026-10-02 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('catalog', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgrant',
            name='current_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_current', to='quiz.quizattempt', verbose_name='当前答卷'),
        ),
        migrations.AddField(
            model_name='quizgrant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='catalog.quizproduct', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='quizgrant',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='catalog.quizversion', verbose_name='题库版本'),
        ),
        migrations.AddIndex(
            model_name='accesscode',
            index=models.Index(fields=['is_activated', 'is_used'], name='access_code_is_acti_3ace50_idx'),
        ),
    ]
