# Generated by Django 5.2.17 on 2026-10-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='encrypted_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='accesscode',
            name='generation',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='旧明文码（迁移后清空）'),
        ),
    ]
